@startgantt VisualLinkerScript Timeline
Project starts 2022-08-1
printscale monthly
[ Research and preparation ] requires 20 days
[ Milestone I ] starts at [ Research and preparation ]'s end
[ Milestone I ] requires 99 days
[ Milestone II ] starts at [ Milestone I ]'s end
[ Milestone II ] requires 122 days
[ Milestone III ] starts at [ Milestone II ]'s end
[ Milestone III ] requires 105 days
[ Parsing Possible  ] happens at [ Milestone III ]'s end
[ Milestone IV ] starts at [ Milestone III ]'s end
[ Milestone IV ] requires 175 days
[ Minimum Viable Product MVP ] happens at [ Milestone IV ]'s end
[ Milestone V ] starts at [ Milestone IV ]'s end
[ Milestone V ] requires 110 days
[ Milestone VI ] starts at [ Milestone V ]'s end
[ Milestone VI ] requires 150 days
[ Release 1.0.0 ] happens at [ Milestone VI ]'s end
[ Milestone VII ] starts at [ Milestone VI ]'s end
[ Milestone VII ] requires 150 days
@endgantt